# Generated by Django 5.2 on 2025-11-14 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ubi_web', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ubicacion',
            name='ciudad',
            field=models.CharField(blank=True, max_length=255, verbose_name='Ciudad'),
        ),
        migrations.AddField(
            model_name='ubicacion',
            name='documento_pdf',
            field=models.FileField(blank=True, null=True, upload_to='ubicaciones/documentos/', verbose_name='Documento PDF'),
        ),
        migrations.AddField(
            model_name='ubicacion',
            name='latitud',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Latitud'),
        ),
        migrations.AddField(
            model_name='ubicacion',
            name='longitud',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Longitud'),
        ),
        migrations.AddField(
            model_name='ubicacion',
            name='mapa_imagen',
            field=models.ImageField(blank=True, null=True, upload_to='ubicaciones/mapas/', verbose_name='Mapa'),
        ),
    ]
