# Generated by Django 5.2 on 2025-11-14 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ubi_web', '0002_ubicacion_ciudad_ubicacion_documento_pdf_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ubicacion',
            name='contenido',
            field=models.TextField(blank=True, help_text='Contenido en formato Markdown para el documento PDF', verbose_name='Contenido (Markdown)'),
        ),
    ]
