# Generated by Django 5.2 on 2025-11-18 23:20

import django.db.models.deletion
import esp_web.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Especificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255)),
                ('contenido', models.TextField(blank=True)),
                ('archivo', models.FileField(blank=True, null=True, upload_to=esp_web.models.especificacion_upload_path)),
                ('token_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('orden', models.PositiveIntegerField(db_index=True, default=0)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'main_especificacion',
                'ordering': ['orden', '-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='EspecificacionImagen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(upload_to=esp_web.models.especificacion_imagen_upload_path)),
                ('descripcion', models.TextField(blank=True, verbose_name='Descripción')),
                ('fecha_subida', models.DateTimeField(auto_now_add=True)),
                ('especificacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagenes', to='esp_web.especificacion')),
            ],
            options={
                'verbose_name': 'Imagen de Especificación',
                'verbose_name_plural': 'Imágenes de Especificaciones',
                'db_table': 'main_especificacionimagen',
                'ordering': ['-fecha_subida'],
            },
        ),
        migrations.CreateModel(
            name='Proyecto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, verbose_name='Nombre de Proyecto')),
                ('solicitante', models.CharField(max_length=200, verbose_name='Solicitante')),
                ('ubicacion', models.CharField(max_length=200, verbose_name='Ubicación')),
                ('descripcion', models.TextField(blank=True, verbose_name='Descripción')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('activo', models.BooleanField(default=True)),
                ('publico', models.BooleanField(default=False, verbose_name='Público')),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='proyectos_creados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Proyecto',
                'verbose_name_plural': 'Proyectos',
                'db_table': 'main_proyecto',
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.AddField(
            model_name='especificacion',
            name='proyecto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='especificaciones', to='esp_web.proyecto'),
        ),
    ]
