/** @type {import('tailwindcss').Config} */
module.exports = {
    content: [
        "./pliego_esp/templates/**/*.html",
        "./pliego_esp/templates/*.html",
        "./pliego_esp/forms.py",
        "./esp_generica/templates/**/*.html",
        "./esp_generica/forms.py",
        "./embeddings/templates/**/*.html",
        "./embeddings/forms.py",
        "./pliego_esp/templates/pasos.html",
        "./prep_doc_gen/templates/**/*.html",
        "./prep_doc_gen/templates/*.html",
        "./prep_doc_gen/forms.py",
        "./main/templates/**/*.html",
        "./templates/**/*.html",
    ],
    theme: {
        extend: {},
    },
    plugins: [
        require('@tailwindcss/forms'),
        require('@tailwindcss/typography'),
        require('@tailwindcss/aspect-ratio'),
        require('daisyui'),
    ],
    daisyui: {
        themes: ["constructor"],
        base: true,
        styled: true,
        utils: true,
        prefix: "",
        logs: true,
        themeRoot: ":root",
    },
    safelist: [
        'bg-blue-600',
        'bg-green-600',
        'bg-red-600',
        'bg-purple-600',
        'bg-indigo-600',
        'bg-teal-600',
        'text-blue-600',
        'text-green-600',
        'text-red-600',
        'text-purple-600',
        'text-indigo-600',
        'text-teal-600',
        'input',
        'bg-yellow-500',
        'bg-yellow-600',
        'text-yellow-600',
        'bg-secondary',
        'bg-primary',
        'bg-primary/10',
        'bg-primary/30',
        'bg-primary/50',
        'bg-primary/70',
        'bg-base-100',
        'bg-base-200',
        'bg-base-300',
        'text-secondary',
        'text-primary',
    ],
}


