# Generated by Django 5.2 on 2025-11-06 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='proyecto',
            name='publico',
            field=models.BooleanField(default=False, verbose_name='Público'),
        ),
    ]
