# Generated by Django 5.2 on 2025-11-08 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_especificacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='especificacion',
            name='fecha_actualizacion',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
