# Generated by Django 5.2 on 2025-11-13 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_especificacion_fecha_actualizacion'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='especificacion',
            options={'ordering': ['orden', '-fecha_creacion']},
        ),
        migrations.AddField(
            model_name='especificacion',
            name='orden',
            field=models.PositiveIntegerField(db_index=True, default=0),
        ),
    ]
