# Generated by Django 5.2 on 2025-11-13 00:52

import django.db.models.deletion
import main.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_especificacion_options_especificacion_orden'),
    ]

    operations = [
        migrations.CreateModel(
            name='EspecificacionImagen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(upload_to=main.models.especificacion_imagen_upload_path)),
                ('fecha_subida', models.DateTimeField(auto_now_add=True)),
                ('especificacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagenes', to='main.especificacion')),
            ],
            options={
                'verbose_name': 'Imagen de Especificación',
                'verbose_name_plural': 'Imágenes de Especificaciones',
                'ordering': ['-fecha_subida'],
            },
        ),
    ]
