# Generated by Django 5.2 on 2025-11-13 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_especificacionimagen'),
    ]

    operations = [
        migrations.AddField(
            model_name='especificacionimagen',
            name='descripcion',
            field=models.TextField(blank=True, verbose_name='Descripción'),
        ),
    ]
