# Generated by Django 5.2 on 2025-11-14 15:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_especificacionimagen_descripcion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='especificacionimagen',
            name='especificacion',
        ),
        migrations.RemoveField(
            model_name='proyecto',
            name='creado_por',
        ),
        migrations.DeleteModel(
            name='Especificacion',
        ),
        migrations.DeleteModel(
            name='EspecificacionImagen',
        ),
        migrations.DeleteModel(
            name='Proyecto',
        ),
    ]
