# Generated by Django 5.2 on 2025-11-25 23:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EspecificacionTecnica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100, verbose_name='Título')),
                ('descripcion', models.TextField(verbose_name='Descripción')),
                ('tipo_servicio', models.CharField(choices=[('Mecánico', 'Mecánico'), ('Eléctrico', 'Eléctrico'), ('Instrumentación', 'Instrumentación'), ('SSMA', 'SSMA (Seguridad, Salud y Medio Ambiente)'), ('Infraestructura / Obras Civiles', 'Infraestructura / Obras Civiles (OOCC)'), ('Mantenimiento de Vehículos', 'Mantenimiento de Vehículos'), ('Laboratorio y Aseguramiento de la Calidad', 'Laboratorio y Aseguramiento de la Calidad'), ('Logística y Distribución', 'Logística y Distribución')], max_length=100, verbose_name='Tipo de Servicio')),
                ('sessionID', models.CharField(blank=True, max_length=255, null=True, verbose_name='Session ID')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, verbose_name='Fecha de Actualización')),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='especificaciones_tecnicas_creadas', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
            ],
            options={
                'verbose_name': 'Especificación Técnica',
                'verbose_name_plural': 'Especificaciones Técnicas',
                'ordering': ['-fecha_creacion'],
            },
        ),
    ]
