# Generated by Django 5.2 on 2025-11-25 23:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('n8n', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Parametros',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parametro', models.CharField(max_length=255, verbose_name='Parámetro')),
                ('valor', models.CharField(blank=True, max_length=255, null=True, verbose_name='Valor Recomendado')),
                ('unidad', models.CharField(blank=True, max_length=50, null=True, verbose_name='Unidad de Medida')),
                ('detalle', models.TextField(blank=True, null=True, verbose_name='Detalle')),
                ('sessionID', models.CharField(blank=True, max_length=255, null=True, verbose_name='Session ID')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, verbose_name='Fecha de Actualización')),
                ('especificacion_tecnica', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parametros', to='n8n.especificaciontecnica', verbose_name='Especificación Técnica')),
            ],
            options={
                'verbose_name': 'Parámetro',
                'verbose_name_plural': 'Parámetros',
                'ordering': ['fecha_creacion'],
            },
        ),
    ]
