# Generated by Django 5.2 on 2025-11-25 23:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('n8n', '0002_parametros'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='parametros',
            options={'ordering': ['parametro'], 'verbose_name': 'Parámetro', 'verbose_name_plural': 'Parámetros'},
        ),
        migrations.RemoveField(
            model_name='parametros',
            name='fecha_actualizacion',
        ),
        migrations.RemoveField(
            model_name='parametros',
            name='fecha_creacion',
        ),
    ]
