# Generated by Django 5.2 on 2025-11-26 00:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('n8n', '0003_alter_parametros_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActividadesAdicionales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255, verbose_name='Nombre')),
                ('valor_recomendado', models.CharField(blank=True, max_length=255, null=True, verbose_name='Valor Recomendado')),
                ('unidad_medida', models.CharField(blank=True, max_length=50, null=True, verbose_name='Unidad de Medida')),
                ('descripcion', models.TextField(blank=True, null=True, verbose_name='Descripción')),
                ('sessionID', models.CharField(blank=True, max_length=255, null=True, verbose_name='Session ID')),
                ('especificacion_tecnica', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actividades_adicionales', to='n8n.especificaciontecnica', verbose_name='Especificación Técnica')),
            ],
            options={
                'verbose_name': 'Actividad Adicional',
                'verbose_name_plural': 'Actividades Adicionales',
                'ordering': ['nombre'],
            },
        ),
    ]
