# Generated by Django 5.2 on 2025-11-26 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('n8n', '0004_actividadesadicionales'),
    ]

    operations = [
        migrations.AddField(
            model_name='especificaciontecnica',
            name='resultado_markdown',
            field=models.TextField(blank=True, null=True, verbose_name='Resultado en Markdown'),
        ),
    ]
