# Generated by Django 5.2 on 2025-11-26 16:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('n8n', '0005_especificaciontecnica_resultado_markdown'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='actividadesadicionales',
            name='sessionID',
        ),
        migrations.RemoveField(
            model_name='especificaciontecnica',
            name='sessionID',
        ),
        migrations.RemoveField(
            model_name='parametros',
            name='sessionID',
        ),
    ]
